name: flutter_background
description: A plugin to keep flutter apps running in the background by using foreground service, wake lock and disabling battery optimizations
version: 0.2.0-nullsafety.0
repository: https://github.com/JulianAssmann/flutter_background
homepage: https://julianassmann.de/

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: de.julianassmann.flutter_background
        pluginClass: FlutterBackgroundPlugin
      # ios:
      #   pluginClass: FlutterBackgroundPlugin
